name: Checkmarx One Scan

on:
  pull_request:
    branches:
        - "main"
        - "master"
        - "test_1"
env:
  platforms: Dockerfile
  scanTypes: iac-security,sast,sca
  threshold: iac-security-high=1,iac-security-medium=1,iac-securitylow=1    
  
jobs:
  security-scan:
    name: Security gate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Security scans
        uses: checkmarx/ast-github-action@main
        with:
          project_name: 163318
          cx_tenant: Cx_Seg
          base_uri: "https://eu.ast.checkmarx.net"
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          additional_params: --iac-security-platforms ${{ env.platform }} --debug --scan-types ${{ env.scanTypes }}
